### ISSUE TITLE
[dev-6.0] Fix ESP32 port

### ISSUE THREAD

**Issue by amirgon** [littlevgl/lv_binding_micropython#28]
Multiple issues need to be fixed on the ESP32 port

- [x] Fix build errors
- [x] Fix indev driver
- [x] Fix display driver
- [x] Crash on runtime when loading display driver
- [x] Crash on runtime when calling obj constructor ( lv.obj())

**Comment by tianzhengtong** [comment]
![log](https://user-images.githubusercontent.com/51434268/60079221-0f3fba00-9760-11e9-93e2-f88eb5113ccf.png)

**Comment by amirgon** [comment]
@tianzhengtong  It's working now.

**You must register a display driver** before you try to creating an lvgl object (since lv_create_* would return NULL otherwise).

To build it for ESP32 + ILI9341:
`make -C ports/esp32 -j4 LV_CFLAGS="-DLV_COLOR_DEPTH=16"`

Here is how a display driver is registered:
https://github.com/littlevgl/lv_binding_micropython/blob/9bd17ae15595fb62375afa8284d1b23859ae0abc/examples/chart_anim_example.py#L40-L56

You can try running [chart_anim_example.py](https://github.com/littlevgl/lv_binding_micropython/blob/9bd17ae15595fb62375afa8284d1b23859ae0abc/examples/chart_anim_example.py)

**Comment by amirgon** [comment]
@tianzhengtong I'm closing this for now.
If you experience more problems, please feel free to open an issue!
