### ISSUE TITLE
[dev-6.0] custom allocators wrong number parameters when stats enabled

### ISSUE THREAD

**Issue by pmp-p** [littlevgl/lv_binding_micropython#29]
Hi, got that on javascript port with dev-6.0 branch when 
```
#define MICROPY_MEM_STATS           (1)
#if MICROPY_MEM_STATS
#define MICROPY_MALLOC_USES_ALLOCATED_SIZE (1)
#endif
```

```
CC ../../lib/lv_bindings/lvgl/src/lv_misc/lv_mem.c
../../lib/lv_bindings/lvgl/src/lv_misc/lv_mem.c:208:36: error: too few arguments to function call, expected 2, have 1
    LV_MEM_CUSTOM_FREE((void *)data);
    ~~~~~~~~~~~~~~~~~~             ^
../../py/misc.h:94:1: note: 'm_free' declared here
void m_free(void *ptr, size_t num_bytes);
^
../../lib/lv_bindings/lvgl/src/lv_misc/lv_mem.c:265:58: error: too few arguments to function call, expected 3, have 2
    void * new_p = LV_MEM_CUSTOM_REALLOC(data_p, new_size);
                   ~~~~~~~~~~~~~~~~~~~~~                 ^
../../py/misc.h:92:1: note: 'm_realloc' declared here
void *m_realloc(void *ptr, size_t old_num_bytes, size_t new_num_bytes);
^
2 errors generated.
```

**Comment by amirgon** [comment]
@pmp-p Yes, I noticed that enabling stats changes memory allocation prototypes. Very awkward in my opinion:  

```c
#if MICROPY_MALLOC_USES_ALLOCATED_SIZE
void m_free(void *ptr, size_t num_bytes) {
#else
void m_free(void *ptr) {
#endif
```

lv_micropython hooks lvgl custom memory allocation functions to micropython memory allocation functions, to take advantage of micropython Garbage Collector.  
However, lvgl custom memory allocation do not pass `num_bytes` on on `free`.

[There's also a remark on the js port "BROKEN"](https://github.com/littlevgl/lv_micropython/blob/ef943a1ab40b32a8a77059d6e833a440446c51e8/ports/javascript/mpconfigport.h#L46
) on that line (that came from micropython upstream) so there may be additional problems with this.  

So currently - this is not supported.
