### ISSUE TITLE
Set the image source of lv_img as a variable through python failed

### ISSUE THREAD

**Issue by xiangweizeng** [littlevgl/lv_binding_micropython#31]
I need to set the picture source of lv_img as a variable through python, but I did not find the binding of lv_img_dsc_t in python binding.

examples/example1.py  report error,   AttributeError: 'module'  has no attribute 'img_dsc_t'.

Thank you!

**Comment by amirgon** [comment]
@xiangweizeng I can't reproduce your problem. `example1.py` works fine for me.

**Please make sure you follow these steps, exactly in this order**:

```
git clone https://github.com/littlevgl/lv_micropython.git
cd lv_micropython/
git checkout dev-6.0
git submodule update --recursive --init
make -C ports/unix
ports/unix/micropython
import lib.lv_bindings.examples.example1
```

(The last step is in micropython REPL)
