### ISSUE TITLE
framebuffer driver on unixport doesn't work on MacOS

### ISSUE THREAD

**Issue by stepansnigirev** [littlevgl/lv_binding_micropython#49]
One of the lvgl drivers for unixport is `modfb`. On MacOS there is no `linux/fb.h`, so `lv_micropython` doesn't compile on Mac without some editing.
I suggest disabling this module in linuxport for mac.

Makefile in `ports/unix` has a handy variable `UNAME_S` that can be used to dynamically enable/disable this module depending on the platform.

**Comment by amirgon** [comment]
Done on [dev-6.1](https://github.com/littlevgl/lv_micropython/tree/dev-6.1).

Could you verify?

**Comment by stepansnigirev** [comment]
Yes, it works now, thanks!
