### ISSUE TITLE
Correctly convert PNG color depth

### ISSUE THREAD

**Issue by amirgon** [littlevgl/lv_binding_micropython#53]
On https://github.com/littlevgl/lv_binding_micropython/blob/dev-6.1/lib/imagetools.py, color depth needs to be converted correctly, the same way `convert_color_depth` is used on https://blog.littlevgl.com/2018-10-05/png_converter.

**Comment by Neutree** [comment]
when I change color depth to 16 in `lv_conf.h`, load image fail~

![image](https://user-images.githubusercontent.com/8625829/70221603-a2573400-1783-11ea-9935-2cb227f4814d.png)

![image](https://user-images.githubusercontent.com/8625829/70221623-ab480580-1783-11ea-99e5-1ec36fb96996.png)

**Comment by amirgon** [comment]
Fixed on ec10079aab374460863065dff72ec6fa96ca35ae
