### ISSUE TITLE
example of working with a rotary encoder?

### ISSUE THREAD

**Issue by dukeduck1984** [littlevgl/lv_binding_micropython#60]
Hi,

Is there an example in micropython available which demostrates how to work with a rotary encoder (and 'groups')?

Thanks,
Kaiyuan

**Comment by amirgon** [comment]
Hi @dukeduck1984 !

**Please send questions to [the forum](https://forum.littlevgl.com/c/micropython)**.  
If it's micropython specific, you can use the micropython category in the forum.




> Is there an example in micropython available which demostrates how to work with a rotary encoder (and 'groups')?

Unfortunately I don't think I've seen such example.  
If you have a C example, it's usually very easy to convert lvgl C examples to Micropython.
