### ISSUE TITLE
only font_roboto_16 & font_roboto_28 available for micropython? 

### ISSUE THREAD

**Issue by dukeduck1984** [littlevgl/lv_binding_micropython#61]
Hi,

How can I use font_roboto_12 and font_roboto_22 in micropython as mentioned in the docs?  I can find only lv.font_roboto_16 & lv.font_roboto_28.

Thanks,
Kaiyuan

**Comment by amirgon** [comment]
**Please send questions to [the forum](https://forum.littlevgl.com/c/micropython)**.  
If it's micropython specific, you can use the micropython category in the forum.
