### ISSUE TITLE
segmentation fault on unix port

### ISSUE THREAD

**Issue by uraich** [littlevgl/lv_binding_micropython#68]
Hi, 
I compiled lv_micropython on my Ubuntu 19.10 machine and I get a segmentation fault when trying to execute SDL.init()
I attach a screen dump of what gdb tells me
![Screenshot from 2020-02-07 18-02-46](https://user-images.githubusercontent.com/1673533/74049307-26bc7200-49d4-11ea-8677-6319a3c34837.png)

**Comment by embeddedt** [comment]
Looks like a duplicate of #46

SDL and/or our MicroPython demo don't play nicely with some/all Nvidia cards; try switching to Intel graphics.

**Comment by embeddedt** [comment]
Closing as there was no response from the OP.
